---
ID: "01b01e7c-a0a1-4e1e-bd79-758432171684"
Parent: "3971c01b-9bcd-4633-9b68-133fed80d477"
Template: "3971c01b-9bcd-4633-9b68-133fed80d477"
Path: /sitecore/templates/Feature/Services/Portfolio Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180802T021949Z
    - ID: "25cd3451-380e-448c-8ea6-f7d6755cb162"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
