---
ID: "c03dcc28-9cc9-4b41-9ccd-e28342db30f4"
Parent: "bb85a828-69c0-4544-9321-b39a54a11a8e"
Template: "bb85a828-69c0-4544-9321-b39a54a11a8e"
Path: /sitecore/templates/Feature/About/Team Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "05ef8496-54f0-49b8-87c4-cccc92c63768"
      Hint: Name
      Value: $name
    - ID: "24dba11c-34c5-490e-9d7b-a59f7616de63"
      Hint: Facebook
      Value: "https://facebook.com"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180804T201331Z
    - ID: "2d640590-a2d1-4be8-a1f9-a51a7aaa8bff"
      Hint: Linkedin
      Value: "https://linkedin.com"
    - ID: "37af2be1-db4f-4453-a3f1-6b1ea4f729eb"
      Hint: Twitter
      Value: "https://twitter.com"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5e8da58d-e5c6-4fb5-ae98-b776890b25cc"
      Hint: Role
      Value: Position
